//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexosConsulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnexosConsulta()
        {
            this.ImagenesAnexos = new HashSet<ImagenesAnexos>();
            this.RecetaMedica = new HashSet<RecetaMedica>();
        }
    
        public int id_anexo { get; set; }
        public Nullable<int> id_consulta { get; set; }
        public string observaciones { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesAnexos> ImagenesAnexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaMedica> RecetaMedica { get; set; }
    }
}
