//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Medico = new HashSet<Medico>();
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int id_usuario { get; set; }
        public int rol { get; set; }
        [Display(Name = "Sexo")]
        public string sexo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de nacimiento")]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        [Display(Name = "Primer nombre")]
        public string primer_nombre { get; set; }
        [Display(Name = "Segundo nombre")]
        public string segundo_nombre { get; set; }
        [Display(Name = "Primer apellido")]
        public string primer_apellido { get; set; }
        [Display(Name = "Segundo apellido")]
        public string segundo_apellido { get; set; }
        [Display(Name = "Nombre de usuario")]
        public string nombre_usuario { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string pass_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medico> Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
